// Canonical list of JAMB subjects — shared across the app.
// Keep in sync with the backend copy at src/lib/jambSubjects.js
export const JAMB_SUBJECTS = [
  "English",
  "Agric Science",
  "Arabic",
  "Fine Art",
  "Biology",
  "Chemistry",
  "Commerce",
  "Computer",
  "CRS",
  "Economics",
  "French",
  "Geography",
  "Government",
  "Hausa",
  "History",
  "Home Econs",
  "Igbo",
  "IRS",
  "Literature",
  "Maths",
  "Music",
  "PHE",
  "Physics",
  "Accounting",
  "Yoruba",
];
